### ISSUE TITLE
Using aux['outs']['z_indices'] for QuantizedAE 

### ISSUE THREAD

**Issue by gulcinbaykal** [kylehkhsu/latent_quantization#2]
Hi,

Thank you for the nice work. I was trying to understand your codes, and I found something puzzling according to my understanding of discrete representations.

[This line](https://github.com/kylehkhsu/latent_quantization/blob/9a420a33505e03914f9b4fbfcafd221d25b8162f/scripts/train_ae.py#L139) sets `aux['z_hat]` as the discrete indices from the codebook where the latent variables are indeed discrete, which is a correct implementation for VQVAE. However, you do not do the same assignment for QLAE even though you set `is_continuous` as False in [this line](https://github.com/kylehkhsu/latent_quantization/blob/9a420a33505e03914f9b4fbfcafd221d25b8162f/disentangle/latents/quantized.py#L18). So, you are using the quantized, and continuous representation to calculate the disentanglement even if you treat QLAE as a discrete model. I was thinking you should do the same assignment like:

`if isinstance(model, disentangle.models.QuantizedAE):`
`    aux['z_hat'] = aux['outs']['z_indices']`

in [this](https://github.com/kylehkhsu/latent_quantization/blob/9a420a33505e03914f9b4fbfcafd221d25b8162f/scripts/train_ae.py#L129) method. 

If I'm missing something or misunderstanding things, I would be really happy if you can clarify it. Thank you for your time.

**Comment by kylehkhsu** [comment]
If I recall correctly, there is no difference for QLAE, as the preprocessing for calculating the disentanglement metrics will discretize the inputs. The reason we do this for VQVAE is to convert from continuous code vectors to scalar integers, but QLAE's continuous representation is already scalar (per codebook).

**Comment by gulcinbaykal** [comment]
I see your point. According to my experiments, two different implementations lead to nearly the same disentanglement results, but I still wanted to ask as I thought using the indices of the quantizing scalars might be conceptually more appropriate. Thank you for your reply.
